site_name: MapsForBlazor

theme:
  name: material
  language: ro
  logo: assets/CAL.png
  favicon: assets/CAL.png

  features:
    - navigation.sections
    - navigation.expand
    # Șterge liniile de mai jos:
    # - toc.integrate
    # - toc.follow
  palette:
    primary: indigo