site_name: MapsForBlazor

theme:
  name: material
  language: ro
  logo: assets/CAL.png
  favicon: assets/CAL.png

  features:
    - navigation.sections
    - navigation.expand

plugins:
  - search

nav:
  - Home: index.md
  - StreamPoint collection: StreamPoint.md
  - Drone Dashboard: Drone.md
#  - Load Parameters: load-parameters.md
#  - Points on the Map: points.md
#  - Appearance: appearance.md
#  - Examples: examples.md